### ISSUE TITLE
Error "Cannot read property 'includes' of null"

### ISSUE THREAD

**Issue by joelb01-github** [vegidio/js-vimdb#2]
Hello,

I can't seem to make this work as I keep getting the same error for any movie I try

```
TypeError: Cannot read property 'includes' of null
    at r.default.scrapShowName (/home/joel/Wanted/Coding/be-api-main/_local-test/node_modules/vimdb/dist/vimdb.js:1:8661)
    at r.default.<anonymous> (/home/joel/Wanted/Coding/be-api-main/_local-test/node_modules/vimdb/dist/vimdb.js:1:5058)
    at Generator.next (<anonymous>)
    at o (/home/joel/Wanted/Coding/be-api-main/_local-test/node_modules/vimdb/dist/vimdb.js:1:4436)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I tried to look into it and it seems the code is looking for the element `"div.title_wrapper > h1"` which returns `null`. 

I've actually tried another scrapper (`imdb`) which seems to have a similar error. I don't know much about html parsing, but could it be the page format changed?

Cheers
Joel

**Comment by vegidio** [comment]
Sorry for the delay, but this should be fixed in version 4.0.1.
By the way, the bundle was converted to ESM so keep that in mind in case your project doesn't support it.
